runtime: python310

handlers:
- url: /
  secure: always
  script: auto
  
- url: /statics
  static_dir: statics
  
- url: /favicon\.ico
  static_files: statics/img/favicon.ico
  upload: statics/img/favicon\.ico